### ISSUE TITLE
add transition delay for tooltip windows

### ISSUE THREAD

**Issue by killarny** [Enderlux/reddit-wallpapers#2]
Sometimes it can be very frustrating to mouse over the tooltips to try to get to the buttons in the tooltip (like "copy permalink") because one wrong mouse drag slightly off the tooltip in the space between the menu and the tooltip makes the whole thing disappear.

Especially because of this area here, where moving the mouse down from the menu, one has to stay within the tiny couple-pixel wide little arrow:

![image](https://user-images.githubusercontent.com/29001/116005729-49857700-a5d6-11eb-9334-86aa2bae7b71.png)

It would be nice if the toolip popup thing had a transition delay of about 1-2s or so, to allow "sloppier" mouse movement.

I've tried messing with the CSS a bit to see if I could send you a MR, but I can't find the right element to anchor to (and I suspect it might need adjusting in the .js)

**Comment by Enderlux** [comment]
i do not want to add a transition delay however i have expanded the mouseover area so there is no gap between the button and the tooltip, thus you don't have to hit the arrow perfectly
